# Generated by Django 5.2.16 on 2026-07-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_confidence_threshold', models.FloatField(default=0.3)),
                ('fire_threshold', models.FloatField(default=0.4)),
                ('smoke_threshold', models.FloatField(default=0.35)),
                ('flood_threshold', models.FloatField(default=0.35)),
                ('accident_threshold', models.FloatField(default=0.35)),
                ('crowd_threshold', models.FloatField(default=0.3)),
                ('road_obstruction_threshold', models.FloatField(default=0.3)),
                ('detection_interval_ms', models.IntegerField(default=2000)),
                ('model_name', models.CharField(choices=[('yolo11n.pt', 'YOLO11 Nano'), ('yolo11s.pt', 'YOLO11 Small'), ('yolo11m.pt', 'YOLO11 Medium')], default='yolo11n.pt', max_length=20)),
                ('enable_sound_alerts', models.BooleanField(default=True)),
                ('enable_push_notifications', models.BooleanField(default=True)),
                ('auto_create_incidents', models.BooleanField(default=True)),
                ('dedup_window_minutes', models.IntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configuration',
            },
        ),
    ]
