# Generated by Django 5.2.16 on 2026-08-21 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Detected', 'Detected'), ('Verified', 'Verified'), ('Dispatched', 'Dispatched'), ('Responding', 'Responding'), ('Resolved', 'Resolved'), ('Archived', 'Archived'), ('Dismissed', 'Dismissed'), ('Note_Added', 'Note Added'), ('Evidence_Added', 'Evidence Added'), ('Severity_Changed', 'Severity Changed'), ('Escalated', 'Escalated')], max_length=25)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Incident Timeline Entry',
                'verbose_name_plural': 'Incident Timeline Entries',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispatch Message',
                'verbose_name_plural': 'Dispatch Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
