# Generated by Django 5.2.16 on 2026-07-19 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0003_incident_archived_at_incident_dismissed_at_and_more'),
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatcher_type', models.CharField(choices=[('Barangay_Tanod', 'Barangay Tanod'), ('Barangay_Official', 'Barangay Official'), ('MDRRMO', 'MDRRMO'), ('BFP', 'BFP'), ('PNP', 'PNP')], default='Barangay_Tanod', max_length=30)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('En_Route', 'En Route'), ('On_Scene', 'On Scene'), ('Unavailable', 'Unavailable')], default='Available', max_length=15)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatcher_profile', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatchers', to='zones.zone')),
            ],
            options={
                'verbose_name': 'Dispatcher',
                'verbose_name_plural': 'Dispatchers',
                'ordering': ['dispatcher_type', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='IncidentTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Detected', 'Detected'), ('Verified', 'Verified'), ('Dispatched', 'Dispatched'), ('Dispatch_Accepted', 'Dispatch Accepted'), ('Dispatch_En_Route', 'Dispatch En Route'), ('Dispatch_On_Scene', 'Dispatch On Scene'), ('Dispatch_Completed', 'Dispatch Completed'), ('Responding', 'Responding'), ('Resolved', 'Resolved'), ('Archived', 'Archived'), ('Dismissed', 'Dismissed'), ('Note_Added', 'Note Added'), ('Evidence_Added', 'Evidence Added'), ('Severity_Changed', 'Severity Changed'), ('Escalated', 'Escalated')], max_length=25)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_actions', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'Incident Timeline Entry',
                'verbose_name_plural': 'Incident Timeline Entries',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('En_Route', 'En Route'), ('On_Scene', 'On Scene'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('en_route_at', models.DateTimeField(blank=True, null=True)),
                ('on_scene_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches_initiated', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='incidents.incident')),
                ('dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='dispatch.dispatcher')),
            ],
            options={
                'verbose_name': 'Dispatch',
                'verbose_name_plural': 'Dispatches',
                'ordering': ['-created_at'],
                'unique_together': {('incident', 'dispatcher')},
            },
        ),
    ]
