# Generated by Django 5.2.15 on 2026-07-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('barangay', models.CharField(max_length=200)),
                ('boundary_coords', models.JSONField(blank=True, default=dict, help_text='Polygon coordinates as GeoJSON-like geometry')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['name'],
            },
        ),
    ]
