# Generated by Django 5.2.15 on 2026-07-04 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responder_type', models.CharField(choices=[('Barangay_Tanod', 'Barangay Tanod'), ('Barangay_Official', 'Barangay Official'), ('MDRRMO', 'MDRRMO'), ('BFP', 'BFP'), ('PNP', 'PNP')], max_length=30)),
                ('suggested_action', models.CharField(choices=[('Verify_Incident', 'Verify Incident'), ('Dispatch_Responders', 'Dispatch Responders'), ('Road_Clearing', 'Road Clearing'), ('Evacuation', 'Evacuation'), ('Emergency_Escalation', 'Emergency Escalation'), ('Continue_Monitoring', 'Continue Monitoring')], max_length=30)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=10)),
                ('explanation', models.TextField(blank=True, default='')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('reasoning', models.TextField(blank=True, default='')),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_recommendations', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'ordering': ['-priority', '-confidence_score', '-created_at'],
            },
        ),
    ]
