# Generated by Django 5.2.16 on 2026-08-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='incident_type',
            field=models.CharField(choices=[('Fire', 'Fire'), ('Smoke', 'Smoke'), ('Vehicle_Accident', 'Vehicle Accident'), ('General', 'General Emergency')], default='General', max_length=30),
        ),
    ]
