# Generated by Django 5.2.16 on 2026-07-19 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout'), ('Incident_Created', 'Incident Created'), ('Incident_Verified', 'Incident Verified'), ('Incident_Dismissed', 'Incident Dismissed'), ('Incident_Dispatched', 'Incident Dispatched'), ('Incident_Resolved', 'Incident Resolved'), ('Incident_Archived', 'Incident Archived'), ('Incident_Updated', 'Incident Updated'), ('Dispatch_Accepted', 'Dispatch Accepted'), ('Dispatch_Rejected', 'Dispatch Rejected'), ('Dispatch_Status', 'Dispatch Status Changed'), ('Recommendation_Accepted', 'Recommendation Accepted'), ('Recommendation_Rejected', 'Recommendation Rejected'), ('Camera_Created', 'Camera Created'), ('Camera_Updated', 'Camera Updated'), ('Camera_Deleted', 'Camera Deleted'), ('User_Created', 'User Created'), ('User_Updated', 'User Updated'), ('User_Deactivated', 'User Deactivated'), ('AI_Config_Changed', 'AI Configuration Changed'), ('Report_Generated', 'Report Generated'), ('Report_Approved', 'Report Approved'), ('Settings_Changed', 'Settings Changed')], max_length=30)),
                ('resource_type', models.CharField(blank=True, default='', max_length=50)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_429f6b_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx')],
            },
        ),
    ]
