# Generated by Django 5.2.16 on 2026-08-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('Login', 'Login'), ('Login_Failed', 'Login Failed'), ('Logout', 'Logout'), ('Account_Locked', 'Account Locked'), ('Password_Reset_Requested', 'Password Reset Requested'), ('Incident_Created', 'Incident Created'), ('Incident_Verified', 'Incident Verified'), ('Incident_Dismissed', 'Incident Dismissed'), ('Incident_Dispatched', 'Incident Dispatched'), ('Incident_Resolved', 'Incident Resolved'), ('Incident_Archived', 'Incident Archived'), ('Incident_Updated', 'Incident Updated'), ('Camera_Created', 'Camera Created'), ('Camera_Updated', 'Camera Updated'), ('Camera_Deleted', 'Camera Deleted'), ('User_Created', 'User Created'), ('User_Updated', 'User Updated'), ('User_Deactivated', 'User Deactivated'), ('AI_Config_Changed', 'AI Configuration Changed'), ('Settings_Changed', 'Settings Changed')], max_length=30),
        ),
    ]
