# Generated by Django 5.2.16 on 2026-08-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('Login', 'Login'), ('Login_Failed', 'Login Failed'), ('Logout', 'Logout'), ('Account_Locked', 'Account Locked'), ('Account_Unlocked', 'Account Unlocked'), ('Password_Reset_Requested', 'Password Reset Requested'), ('Password_Reset_Completed', 'Password Reset Completed'), ('Incident_Created', 'Incident Created'), ('Incident_Verified', 'Incident Verified'), ('Incident_Dismissed', 'Incident Dismissed'), ('Incident_Dispatched', 'Incident Dispatched'), ('Incident_Resolved', 'Incident Resolved'), ('Incident_Archived', 'Incident Archived'), ('Incident_Updated', 'Incident Updated'), ('Camera_Created', 'Camera Created'), ('Camera_Updated', 'Camera Updated'), ('Camera_Deleted', 'Camera Deleted'), ('User_Created', 'User Created'), ('User_Updated', 'User Updated'), ('User_Deactivated', 'User Deactivated'), ('AI_Config_Changed', 'AI Configuration Changed'), ('Settings_Changed', 'Settings Changed'), ('Profile_Updated', 'Profile Updated'), ('Password_Changed', 'Password Changed'), ('Email_Change_Requested', 'Email Change Requested'), ('Email_Change_Completed', 'Email Change Completed'), ('Chief_Mode_Entered', 'Chief Mode Entered'), ('Chief_Mode_Exited', 'Chief Mode Exited'), ('Two_Factor_Enabled', 'Two-Factor Authentication Enabled'), ('Two_Factor_Disabled', 'Two-Factor Authentication Disabled'), ('Two_Factor_Verified', 'Two-Factor Verification Successful'), ('Two_Factor_Failed', 'Two-Factor Verification Failed')], max_length=30),
        ),
    ]
