# Generated by Django 5.2.16 on 2026-10-09 09:08

from django.db import migrations, models


def rename_incident_created(apps, schema_editor):
    """Historical rows stored "Incident_Created"; the action is now
    Incident_Detected, so rename them to keep history consistent."""
    AuditLog = apps.get_model("audit", "AuditLog")
    AuditLog.objects.filter(action="Incident_Created").update(action="Incident_Detected")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_normalize_audit_action_values'),
    ]

    operations = [
        migrations.RunPython(rename_incident_created, noop),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('Login', 'Login'), ('Login_Failed', 'Login Failed'), ('Logout', 'Logout'), ('Account_Locked', 'Account Locked'), ('Account_Unlocked', 'Account Unlocked'), ('Password_Reset_Requested', 'Password Reset Requested'), ('Password_Reset_Completed', 'Password Reset Completed'), ('Incident_Detected', 'Incident Detected'), ('Incident_Verified', 'Incident Verified'), ('Incident_Dismissed', 'Incident Dismissed'), ('Incident_Dispatched', 'Incident Dispatched'), ('Incident_Resolved', 'Incident Resolved'), ('Incident_Archived', 'Incident Archived'), ('Incident_Updated', 'Incident Updated'), ('Camera_Created', 'Camera Created'), ('Camera_Updated', 'Camera Updated'), ('Camera_Deleted', 'Camera Deleted'), ('User_Created', 'User Created'), ('User_Updated', 'User Updated'), ('User_Deactivated', 'User Deactivated'), ('AI_Config_Changed', 'AI Configuration Changed'), ('Settings_Changed', 'Settings Changed'), ('Profile_Updated', 'Profile Updated'), ('Password_Changed', 'Password Changed'), ('Email_Change_Requested', 'Email Change Requested'), ('Email_Change_Completed', 'Email Change Completed'), ('Chief_Mode_Entered', 'Chief Mode Entered'), ('Chief_Mode_Exited', 'Chief Mode Exited'), ('Two_Factor_Enabled', 'Two-Factor Authentication Enabled'), ('Two_Factor_Disabled', 'Two-Factor Authentication Disabled'), ('Two_Factor_Verified', 'Two-Factor Verification Successful'), ('Two_Factor_Failed', 'Two-Factor Verification Failed'), ('Agreement_Accepted', 'Agreement Accepted')], max_length=30),
        ),
    ]