# Generated by Django 5.2.15 on 2026-07-04 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(max_length=30)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('bbox_coords', models.JSONField(blank=True, default=dict, help_text='Bounding box coordinates [x1, y1, x2, y2]')),
                ('fps', models.FloatField(blank=True, null=True)),
                ('frame_timestamp', models.DateTimeField(blank=True, null=True)),
                ('snapshot_image', models.ImageField(blank=True, null=True, upload_to='detections/')),
                ('is_verified', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='cameras.camera')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'Detection',
                'verbose_name_plural': 'Detections',
                'ordering': ['-created_at'],
            },
        ),
    ]
