# Generated by Django 5.2.16 on 2026-08-21 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detections', '0001_initial'),
        ('incidents', '0001_initial'),
        ('lookups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='detection',
            name='incident_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detections', to='lookups.incidenttype'),
        ),
    ]
