# Generated by Django 5.2.16 on 2026-09-28 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_detections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detection',
            name='verdict',
            field=models.CharField(choices=[('pending', 'Pending'), ('true', 'True incident'), ('false', 'False positive')], default='pending', help_text='Operator verdict: real incident or false positive.', max_length=10),
        ),
        migrations.AlterField(
            model_name='detection',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='True once a human has reviewed this detection (any verdict).'),
        ),
    ]
