# Generated by Django 5.2.15 on 2026-07-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('Detected', 'Detected'), ('Verified', 'Verified'), ('Responding', 'Responding'), ('Resolved', 'Resolved'), ('Dismissed', 'Dismissed')], default='Detected', max_length=10),
        ),
    ]
