# Generated by Django 5.2.16 on 2026-09-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='detection_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='incident',
            name='source',
            field=models.CharField(choices=[('ai', 'AI Detection'), ('simulation', 'Simulation'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
    ]
