# Generated by Django 5.2.16 on 2026-10-02 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
        ('incidents', '0002_incident_detection_count_incident_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='cameras.camera'),
        ),
    ]
