# Generated by Django 5.2.16 on 2026-08-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_incident_archived_at_incident_dismissed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('Fire', 'Fire'), ('Smoke', 'Smoke'), ('Vehicle_Accident', 'Vehicle Accident')], max_length=30),
        ),
    ]
