# Generated by Django 5.2.16 on 2026-07-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Operator', 'Operator'), ('Viewer', 'Viewer'), ('Barangay_Official', 'Barangay Official'), ('Barangay_Tanod', 'Barangay Tanod')], default='Viewer', max_length=20),
        ),
    ]
