# Generated by Django 5.2.16 on 2026-08-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Operator', 'Operator'), ('Tanod', 'Barangay Tanod')], default='Tanod', max_length=20),
        ),
    ]
