# Generated by Django 5.2.16 on 2026-08-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('English', 'English'), ('Filipino', 'Filipino')], default='English', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
