# Generated by Django 5.2.16 on 2026-08-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailchangecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailchangecode',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailchangecode',
            name='new_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
