# Generated by Django 5.2.16 on 2026-08-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_trusteddevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreement_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='agreement_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
