import io
import os
import logging
from datetime import datetime, timedelta
from datetime import timezone as dt_timezone
from zoneinfo import ZoneInfo
from django.conf import settings
from django.db.models import Count
from django.http import FileResponse
from django.utils import timezone
from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment

from apps.incidents.models import Incident
from .models import Report
from .serializers import ReportSerializer, ReportGenerateSerializer

logger = logging.getLogger(__name__)


class ReportViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Report.objects.select_related("generated_by").all()
    serializer_class = ReportSerializer
    permission_classes = [IsAuthenticated]
    ordering_fields = ["created_at", "report_type"]

    @action(detail=False, methods=["post"], url_path="generate")
    def generate(self, request) -> Response:
        serializer = ReportGenerateSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        data = serializer.validated_data
        report_type = data["report_type"]
        start = data["date_range_start"]
        end = data["date_range_end"]
        title = data.get(
            "title",
            f"{report_type} Report ({start.date()} - {end.date()})",
        )
        parameters = data.get("parameters", {})

        # Extend end date to end-of-day in Asia/Manila so full day is included
        manila_tz = ZoneInfo("Asia/Manila")
        if timezone.is_naive(end):
            end_aware = timezone.make_aware(end, manila_tz)
        else:
            end_aware = end.astimezone(manila_tz)
        end_of_day = end_aware.replace(hour=23, minute=59, second=59, microsecond=999999)
        end_utc = end_of_day.astimezone(dt_timezone.utc)

        if timezone.is_naive(start):
            start_aware = timezone.make_aware(start, manila_tz)
        else:
            start_aware = start.astimezone(manila_tz)
        start_utc = start_aware.astimezone(dt_timezone.utc)

        incidents = Incident.objects.filter(
            detected_at__gte=start_utc, detected_at__lte=end_utc
        )

        report = Report.objects.create(
            title=title,
            report_type=report_type,
            generated_by=request.user,
            date_range_start=start_utc,
            date_range_end=end_utc,
            parameters=parameters,
        )

        self._generate_pdf(report, incidents)
        self._generate_excel(report, incidents)

        logger.info("Report %s generated by %s", report.id, request.user.username)
        return Response(ReportSerializer(report).data, status=status.HTTP_201_CREATED)

    @action(detail=True, methods=["get"], url_path="download-pdf")
    def download_pdf(self, request, pk=None) -> Response:
        report = self.get_object()
        if not report.file_pdf:
            return Response(
                {"error": "PDF file not available."},
                status=status.HTTP_404_NOT_FOUND,
            )
        return FileResponse(
            report.file_pdf.open("rb"),
            content_type="application/pdf",
            filename=os.path.basename(report.file_pdf.name),
        )

    @action(detail=True, methods=["post"], url_path="approve")
    def approve(self, request, pk=None) -> Response:
        report = self.get_object()
        if report.is_approved:
            return Response({"error": "Report already approved"}, status=400)
        report.is_approved = True
        report.approved_by = request.user
        from django.utils import timezone
        report.approved_at = timezone.now()
        report.save()
        logger.info("Report %s approved by %s", report.id, request.user.username)
        return Response(ReportSerializer(report).data)

    @action(detail=True, methods=["get"], url_path="download-excel")
    def download_excel(self, request, pk=None) -> Response:
        report = self.get_object()
        if not report.file_excel:
            return Response(
                {"error": "Excel file not available."},
                status=status.HTTP_404_NOT_FOUND,
            )
        return FileResponse(
            report.file_excel.open("rb"),
            content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            filename=os.path.basename(report.file_excel.name),
        )

    def _generate_pdf(self, report: Report, incidents) -> None:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        styles = getSampleStyleSheet()
        elements = []

        elements.append(Paragraph(report.title, styles["Title"]))
        elements.append(Spacer(1, 12))
        elements.append(
            Paragraph(
                f"Period: {report.date_range_start.date()} to {report.date_range_end.date()}",
                styles["Normal"],
            )
        )
        elements.append(
            Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles["Normal"])
        )
        elements.append(Spacer(1, 12))

        summary = incidents.values("incident_type").annotate(
            count=Count("id")
        ).order_by("incident_type")

        table_data = [["Incident Type", "Count"]]
        for item in summary:
            table_data.append([item["incident_type"], str(item["count"])])

        table = Table(table_data)
        table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563EB")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
            ])
        )
        elements.append(table)
        doc.build(elements)

        pdf_dir = settings.MEDIA_ROOT / "reports" / "pdf"
        os.makedirs(pdf_dir, exist_ok=True)
        filename = f"report_{report.id}.pdf"
        filepath = pdf_dir / filename
        with open(filepath, "wb") as f:
            f.write(buffer.getvalue())
        report.file_pdf.name = f"reports/pdf/{filename}"
        report.save(update_fields=["file_pdf"])

    def _generate_excel(self, report: Report, incidents) -> None:
        wb = Workbook()
        ws = wb.active
        ws.title = "Incident Report"

        header_font = Font(bold=True, color="FFFFFF", size=12)
        header_fill = PatternFill(start_color="2563EB", end_color="2563EB", fill_type="solid")
        header_alignment = Alignment(horizontal="center", vertical="center")

        headers = [
            "ID", "Type", "Severity", "Status", "Camera", "Zone",
            "Confidence", "Description", "Detected At", "Duration",
        ]
        for col, header in enumerate(headers, 1):
            cell = ws.cell(row=1, column=col, value=header)
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = header_alignment

        for row, inc in enumerate(incidents, 2):
            ws.cell(row=row, column=1, value=inc.id)
            ws.cell(row=row, column=2, value=inc.incident_type)
            ws.cell(row=row, column=3, value=inc.severity)
            ws.cell(row=row, column=4, value=inc.status)
            ws.cell(row=row, column=5, value=inc.camera.name if inc.camera else "")
            ws.cell(row=row, column=6, value=inc.zone.name if inc.zone else "")
            ws.cell(row=row, column=7, value=inc.confidence_score)
            ws.cell(row=row, column=8, value=inc.description[:100] if inc.description else "")
            ws.cell(row=row, column=9, value=inc.detected_at.strftime("%Y-%m-%d %H:%M") if inc.detected_at else "")
            ws.cell(
                row=row, column=10,
                value=str(inc.duration) if inc.duration else "",
            )

        ws.column_dimensions["A"].width = 8
        ws.column_dimensions["B"].width = 20
        ws.column_dimensions["C"].width = 12
        ws.column_dimensions["D"].width = 14
        ws.column_dimensions["E"].width = 20
        ws.column_dimensions["F"].width = 20
        ws.column_dimensions["G"].width = 12
        ws.column_dimensions["H"].width = 40
        ws.column_dimensions["I"].width = 20
        ws.column_dimensions["J"].width = 15

        excel_dir = settings.MEDIA_ROOT / "reports" / "excel"
        os.makedirs(excel_dir, exist_ok=True)
        filename = f"report_{report.id}.xlsx"
        filepath = excel_dir / filename
        wb.save(str(filepath))
        report.file_excel.name = f"reports/excel/{filename}"
        report.save(update_fields=["file_excel"])
