# Generated by Django 5.2.16 on 2026-10-09 07:33

from django.db import migrations, models


def dedupe_camera_names(apps, schema_editor):
    """Rename duplicate camera names so the unique constraint can apply.

    Later instances of a duplicate keep their name; earlier ones get a
    suffix (name>1, name>2...) appended to distinguish them.
    """
    Camera = apps.get_model("cameras", "Camera")
    seen = {}
    for camera in Camera.objects.order_by("id"):
        name = camera.name
        count = seen.get(name, 0)
        if count:
            camera.name = f"{name} ({count + 1})"
            camera.save(update_fields=["name"])
        seen[name] = count + 1


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(dedupe_camera_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]