# Generated by Django 5.2.15 on 2026-07-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='stream_type',
            field=models.CharField(choices=[('RTSP', 'RTSP'), ('HTTP', 'HTTP'), ('MP4', 'MP4'), ('EMBED', 'EMBED')], default='RTSP', max_length=10),
        ),
    ]
