import { Modal, Stack, Text, ScrollArea, Box, Group, Title, ActionIcon, Button, Image } from '@mantine/core';

export interface TermsAndConditionsModalProps {
  opened: boolean;
  onClose: () => void;
  /** When provided (agreement flow), shows "I Understand & Accept" which checks the agreement checkbox. */
  onAcknowledge?: () => void;
}

const INTRO = `Effective Date: August 30, 2026

These Terms of Use govern access to and use of AERIS (AI-Assisted Barangay CCTV Incident Detection and Decision Support System), a system developed to assist authorized personnel of Barangay Sampaloc, Apalit, Pampanga, in monitoring designated CCTV feeds, identifying potential public-safety incidents, managing incident records, and supporting incident-response decisions.

By accessing or using AERIS, users agree to comply with these Terms of Use and the applicable policies governing the system. Access is limited to individuals authorized by the appropriate barangay authority.`;

const SECTIONS = [
  {
    title: '1. Purpose of the System',
    body: `AERIS is designed to assist in monitoring and managing selected public-safety incidents, particularly fire-related incidents and vehicular accidents. Through AI-assisted video analysis, the system helps identify potential incidents and provides relevant information to authorized personnel. AERIS serves as a decision-support tool and does not replace human judgment or the responsibilities of barangay personnel and emergency responders.`,
  },
  {
    title: '2. AI-Assisted Incident Detection',
    body: `AERIS analyzes supported CCTV feeds to identify possible incidents. The results generated by the system are preliminary alerts and must not be treated as confirmed incidents without proper human verification. Authorized personnel are responsible for reviewing detected events, checking the available information, and determining whether further action or escalation is necessary.

The system may fail to detect certain incidents or produce inaccurate classifications, false alarms, or delayed alerts. Its performance may be affected by camera quality, lighting, visibility, network connectivity, and other technical conditions. AERIS does not guarantee that every incident will be detected accurately or immediately.`,
  },
  {
    title: '3. Authorized Access and User Responsibilities',
    body: `Only personnel authorized by the appropriate barangay authority may access and use AERIS. Users are responsible for keeping their login credentials confidential, protecting their accounts from unauthorized access, and using the system only for legitimate barangay operations within the scope of their assigned duties.

All information accessed or recorded through AERIS must be handled responsibly and in accordance with applicable barangay policies, security procedures, and data-protection requirements. Users who enter, review, or confirm incident information must ensure that the details are accurate to the best of their knowledge. Any suspected unauthorized access, compromised account, or security concern must be reported immediately to the designated system administrator.

Users must not share their accounts, allow unauthorized individuals to use the system, or access information and functions beyond their assigned permissions.`,
  },
  {
    title: '4. Prohibited Use',
    body: `AERIS must not be used for unauthorized surveillance, personal interests, harassment, intimidation, discrimination, or the improper targeting of any individual or group. Users are prohibited from accessing restricted CCTV feeds or incident records without authorization, manipulating or falsifying system information, bypassing security controls, or interfering with the proper operation of the system.

Copying, downloading, recording, distributing, or disclosing CCTV footage and incident information without proper authorization is also prohibited. The system must be used solely for its intended public-safety purposes and must not be used for activities that violate applicable laws, privacy requirements, or established barangay policies.

Violations of these Terms of Use may result in the suspension or revocation of system access and may be referred to the appropriate barangay authority for further action, subject to applicable rules and laws.`,
  },
  {
    title: '5. CCTV Feeds and Video Information',
    body: `AERIS may receive video streams from compatible IP-based CCTV cameras through supported streaming protocols, including RTSP. Access to these feeds is restricted to authorized personnel and must be limited to legitimate operational purposes.

Users must observe the applicable Privacy Policy and follow established procedures for viewing, handling, storing, and disclosing CCTV footage. Video recordings and related information must not be used, shared, or retained for unauthorized purposes.`,
  },
  {
    title: '6. System Availability and Technical Limitations',
    body: `The availability of AERIS depends on the proper operation of CCTV cameras, network connections, power supplies, hardware, software, and other supporting components. Service interruptions or performance issues may occur because of equipment failure, poor lighting, limited camera visibility, network instability, or other technical problems.

The system may also produce missed detections, inaccurate classifications, false alarms, or delayed notifications. Users must consider these limitations when reviewing system results and must not rely solely on AI-generated alerts when other relevant information is available. Potential incidents must be assessed through appropriate verification procedures and other available sources of information.`,
  },
  {
    title: '7. Incident Records and Verification',
    body: `Incident information recorded in AERIS must be reviewed and handled responsibly. Users who create, update, review, or confirm incident records are responsible for ensuring that the information is accurate and supported by available evidence.

AI-generated results must undergo human verification before they are treated as confirmed incidents or included in official reports. Any corrections or updates to incident records must follow the system's authorized procedures to maintain the accuracy and reliability of the information.`,
  },
  {
    title: '8. System Security and Confidentiality',
    body: `All users are responsible for helping protect AERIS against unauthorized access, misuse, and disclosure of information. Account credentials must be kept secure, and confidential system information must not be shared with individuals who are not authorized to receive it.

Suspected security incidents, compromised accounts, unauthorized access, or improper disclosure of information must be reported immediately to the designated system administrator or appropriate barangay authority. Users must also follow established security procedures and cooperate with authorized reviews when necessary to maintain the safety and proper operation of the system.`,
  },
  {
    title: '9. Suspension and Revocation of Access',
    body: `Access to AERIS may be suspended or revoked when a user's authorization ends, when access is no longer necessary for assigned duties, or when a violation of these Terms of Use or applicable policies is identified. Any suspension or revocation shall be handled by the appropriate barangay authority in accordance with established procedures and applicable rules.`,
  },
  {
    title: '10. Changes to These Terms',
    body: `These Terms of Use may be revised to reflect changes in the AERIS system, barangay operations, security requirements, or applicable laws and regulations. The latest approved version shall be made available to authorized users.

Users are expected to review and comply with any revisions communicated by the responsible authority. Where renewed acknowledgment is required, users must acknowledge the updated terms before continuing to use the system.`,
  },
  {
    title: '11. Contact and Support',
    body: `Questions concerning these Terms of Use, requests for technical assistance, and reports of security concerns should be directed to the designated barangay administrator or authorized system administrator.`,
  },
];

const FOOTER = `Project AERIS
Barangay Sampaloc, Apalit, Pampanga
For authorized barangay use only.`;

export default function TermsAndConditionsModal({ opened, onClose, onAcknowledge }: TermsAndConditionsModalProps) {
  return (
    <Modal
      opened={opened}
      onClose={onClose}
      withCloseButton={false} // Custom header close button used instead
      centered
      size="lg"
      radius="lg"
      padding="xl"
    >
      {/* Custom Header Section - Matching Reference Aesthetic */}
      <Group justify="space-between" align="flex-start" mb="lg">
        <Group align="center" gap="md">
          <Image src="/icon.png" alt="Aeris Logo" w={90} />
          <Stack gap={2}>
            <Title order={3} fw={700}>Terms of Use</Title>
            <Text size="sm" c="dimmed">
              Please review the system usage guidelines below.
            </Text>
          </Stack>
        </Group>
        <ActionIcon variant="transparent" color="gray" onClick={onClose}>
          <i className='bx bx-x' style={{ fontSize: '24px' }}></i>
        </ActionIcon>
      </Group>

      <hr style={{ border: '0.5px solid #eee', marginBottom: '20px' }} />

      {/* Main Content Area */}
      <ScrollArea.Autosize mah="50vh" mx={-10} px={10} type="hover">
        <Stack gap="lg">
          <Text size="md" c="dimmed" lh={1.6} style={{ whiteSpace: 'pre-line', textAlign: 'justify' }}>
            {INTRO}
          </Text>

          {SECTIONS.map((s) => (
            <Box key={s.title}>
              <Text size="md" fw={700} mb={4} style={{ color: 'var(--mantine-color-text)' }}>
                {s.title}
              </Text>
              <Text size="md" c="dimmed" lh={1.6} style={{ whiteSpace: 'pre-line', textAlign: 'justify' }}>
                {s.body}
              </Text>
            </Box>
          ))}

          <Text size="md" c="dimmed" lh={1.6} style={{ whiteSpace: 'pre-line', textAlign: 'justify' }}>
            {FOOTER}
          </Text>
        </Stack>
      </ScrollArea.Autosize>

      {/* Footer Action - Matching Button Aesthetic */}
      <Box mt="xl">
        {onAcknowledge ? (
          <Button
            fullWidth
            bg="#FF5722"
            radius="md"
            size="md"
            h={48}
            onClick={onAcknowledge}
            styles={{ root: { backgroundColor: '#FF5722' } }}
          >
            I Understand & Accept
          </Button>
        ) : (
          <Button
            fullWidth
            variant="default"
            radius="md"
            size="md"
            h={48}
            onClick={onClose}
          >
            Close
          </Button>
        )}
      </Box>
    </Modal>
  );
}